apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: convomark-staging

bases:
  - ../../base/

patchesStrategicMerge:
  - container-resources.yml
  - replica-count.yml
  - ingress.yml

configMapGenerator:
  - literals:
      - WEB_DOMAIN=https://convomark-staging.server.matteojoliveau.com
      - FRONTEND_DOMAIN=https://develop--convomark.netlify.com
      - LOG_LEVEL=debug
      - REDIS_HOST=redis
      - TELEGRAM_BOT_MAINTENANCE=no
      - SENTRY_DSN=https://c42503061d8d4f2b95a312d84bae60c7@sentry.io/1492000
      - SENTRY_CURRENT_ENV=staging
    name: app-config
